title: Knowledgeâ€¢Day
description: > # this means to ignore newlines until "baseurl:"
  The only blog-cum-newsletter about everything! No pointers, pure content. <br/>
  Charge your curiosity, It's free Knowledge!.
permalink: ':title/'
baseurl: "/KnowledgeDay" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: KnowledgeDayNL #if your site has a twitter account, enter it here

# Author Settings
author: Yash Yadav # add your name
author-img: KD_profile.jpg # add your photo
about-author: I am a software engineer focusing on back-end development. Always hungry to keep learning. # add description
social-twitter: OhY4sh # add your Twitter handle
social-facebook: OhY4sh # add your Facebook handle
social-github: OhYash # add your Github handle
social-linkedin: OhYash # add your Linkedin handle
social-email: KnowledgeDay@protonmail.com # add your Email address

# Disqus
discus-identifier: knowledgeday # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
