title: Anamii's Blog
description: > # this means to ignore newlines until "baseurl:"
  Anamii posts insightful and inspiring articles on different personal
  and spiritual development related topics, such as transformation
  journies, yoga, meditation, vedic teachings, etc.
permalink: ':title/'
baseurl: "" # the subpath 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Anamii  # add your name
author-img: anamii-logo.png # add your photo
about-author: Here we post inspiring and insightful content on personal development and inner transformation topics. # add description
social-twitter: AnamiiOfficial
social-facebook: anamiiofficial
social-linkedin: anamii
social-instagram: anamiiofficial
social-email: contact@anamii.com

# Disqus
discus-identifier: anamii # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
