title: Hola, Soy Sergio Susa, Ingeniero de Sistemas y Computación entre otras cosas.
description: > # this means to ignore newlines until "baseurl:"
  Bienvenidos a mi blog personal donde comparto mis experiencias y vivencias
  y en general todo lo que creo que va a ser de interés general.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sergiosusa.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sergio Susa
author-img: sergio-susa.jpg # add your photo
about-author: Soy un ingeniero de sistemas y computación por vocación, metalero de corazón y video jugador por elección.  # add description
social-twitter: sergiosusa # add your Twitter handle
social-facebook: sergiosusa # add your Facebook handle
social-github: sergiosusa # add your Github handle
social-linkedin: sergiosusa # add your Linkedin handle
social-email: sergio@sergiosusa.com # add your Email address

personal-podcast-title: ¿Qué me estás container?
personal-podcast-url: https://open.spotify.com/show/1FBSbmyYqo9AYbFehaoIWu?si=6fiuPtc7RNOudxJljzCdeA
personal-podcast-image: que-me-estas-container-banner.jpg

todoestamal-podcast-title: Todo está mal
todoestamal-podcast-url: https://open.spotify.com/show/7lSX0GlROui9UFK6SsJY3u?si=tIXMllc5RnGNolIG7YnOkA
todoestamal-podcast-image: todo-esta-mal-banner.jpg

# Disqus
discus-identifier: sergio-susa # add your discus identifier

# Tracker
analytics: UA-65020023-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
