title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/Aimonk" # the subpath of your site, e.g. /blog
url: "https://el-do-rado.github.io/Aimonk/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Aniket Sangohi # add your name
author-img: david-freeman.jpg # add your photo
about-author: Machine Learning Developer # add description
social-twitter: El__Do_RaDo# add your Twitter handle
social-facebook: # add your Facebook handle
social-github: El-Do-RaDo # add your Github handle
social-linkedin: aniket-sangohi-883252128/  # add your Linkedin handle
social-email: manjaniket@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
